# Generated by Django 5.1 on 2024-10-17 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_company_cover_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBurgerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TOP 3 BURGUERS', max_length=100)),
                ('location', models.CharField(default='en San Jose', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopBurgerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('featured_image', models.ImageField(upload_to='top_burgers/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.company')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.topburgersection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
