# Generated by Django 5.1 on 2024-10-17 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_topburgersection_topburgeritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topburgeritem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_burger_items', to='marketplace.company'),
        ),
        migrations.AlterField(
            model_name='topburgeritem',
            name='featured_image',
            field=models.ImageField(help_text='Featured burger image', upload_to='top_burgers/'),
        ),
        migrations.AlterField(
            model_name='topburgeritem',
            name='order',
            field=models.IntegerField(help_text='Position in the top (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='topburgeritem',
            unique_together={('section', 'order')},
        ),
    ]
