# Generated by Django 5.1 on 2024-10-17 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_topburgeritem_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topburgersection',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='topburgeritem',
            name='custom_url',
            field=models.URLField(blank=True, help_text='Custom URL for banner items', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topburgeritem',
            name='item_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('BANNER', 'Banner')], default='COMPANY', max_length=10),
        ),
        migrations.AddField(
            model_name='topburgersection',
            name='position',
            field=models.IntegerField(default=0, help_text='Position order for displaying sections'),
        ),
        migrations.AlterField(
            model_name='topburgeritem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_burger_items', to='marketplace.company'),
        ),
    ]
