# Generated by Django 5.1 on 2024-10-21 01:56

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_companycategory_country_company_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AddField(
            model_name='country',
            name='flag_icon',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Icono de la bandera del país (opcional)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(choices=[('AR', '🇦🇷 Argentina'), ('BO', '🇧🇴 Bolivia'), ('BR', '🇧🇷 Brasil'), ('CL', '🇨🇱 Chile'), ('CO', '🇨🇴 Colombia'), ('CR', '🇨🇷 Costa Rica'), ('CU', '🇨🇺 Cuba'), ('DO', '🇩🇴 República Dominicana'), ('EC', '🇪🇨 Ecuador'), ('SV', '🇸🇻 El Salvador'), ('GT', '🇬🇹 Guatemala'), ('HN', '🇭🇳 Honduras'), ('MX', '🇲🇽 México'), ('NI', '🇳🇮 Nicaragua'), ('PA', '🇵🇦 Panamá'), ('PY', '🇵🇾 Paraguay'), ('PE', '🇵🇪 Perú'), ('PR', '🇵🇷 Puerto Rico'), ('UY', '🇺🇾 Uruguay'), ('VE', '🇻🇪 Venezuela')], max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='El código del país debe ser de 2 letras mayúsculas', regex='^[A-Z]{2}$')]),
        ),
    ]
