# Generated by Django 5.1 on 2024-10-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_days', models.JSONField(default=list)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='marketplace.company')),
            ],
        ),
    ]
