# Generated by Django 5.1 on 2024-10-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_businesshours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshours',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='open_days',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='open_time',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='friday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='friday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='monday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='monday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='saturday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='saturday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='sunday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='sunday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='thursday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='thursday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='tuesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='tuesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='wednesday_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='wednesday_open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
