# Generated by Django 5.1 on 2024-10-22 00:02

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_remove_businesshours_close_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('terms_conditions', models.TextField(verbose_name='Términos y Condiciones')),
                ('discount_type', models.CharField(choices=[('VALUE', 'Valor'), ('PERCENTAGE', 'Porcentaje')], max_length=10, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Descuento')),
                ('banner', cloudinary.models.CloudinaryField(help_text='Banner de la promoción', max_length=255, verbose_name='image')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='marketplace.category', verbose_name='Categoría')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='marketplace.company', verbose_name='Empresa')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='marketplace.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
            },
        ),
    ]
