# Generated by Django 5.1 on 2024-10-22 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Descuento'),
        ),
    ]
