# Generated by Django 5.1 on 2024-11-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_alter_promotion_discount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='company',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='topburgeritem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topburgeritem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='topburgeritem',
            name='section',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('SERVICIOS', 'Categoría Servicios'), ('PRODUCTOS', 'Categoría Productos')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='BusinessHours',
        ),
        migrations.DeleteModel(
            name='CompanyCategory',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='TopBurgerItem',
        ),
        migrations.DeleteModel(
            name='TopBurgerSection',
        ),
    ]
