# Generated by Django 5.1 on 2024-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_remove_company_category_remove_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nit',
            field=models.CharField(blank=True, help_text='Número de Identificación Tributaria', max_length=20, null=True),
        ),
    ]
