# Generated by Django 5.1 on 2024-11-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_company_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso base para el precio (ej: 500 para 500g)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_weight_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('g', 'Gramos'), ('kg', 'Kilogramos')], default='g', max_length=2, null=True),
        ),
    ]
