# Generated by Django 5.1 on 2024-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'Cliente Usuario', 'verbose_name_plural': 'Clientes Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='identification_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Número de Identificación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='identification_type',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PS', 'Pasaporte'), ('NIT', 'NIT')], default=0, max_length=3, verbose_name='Tipo de Identificación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(blank=True, default=30065, max_length=15, verbose_name='Número de Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
